spring:
  profiles.active: producction
  main:
    web-application-type: reactive
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: xxxxxxx
    password: xxxxxx
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false  
server:
  port: 8080
---
spring:
  profiles: develop
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: SA
    password:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      pool-name: H2-POOL
---
spring:
  profiles: producction
  datasource:
   type: com.zaxxer.hikari.HikariDataSource
   url: jdbc:mysql://localhost/crypto_gateway?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   username: root
   password: root
   hikari:
    connection-timeout: 60000
    maximum-pool-size: 20
    idle-timeout: 600000
    max-lifetime: 1800000
    connection-test-query: SELECT 1
    pool-name: MYSQL-POOL
---
logging:
  level:
    sql: debug
    ROOT: info